= Sabacc House Rules

== The Deal

Players place antes to the main pot and the sabacc pot.
Dealer shuffles the deck gives three down cards and one up card to each player.
The dealer lays seven cards face-up on the board in a "flower" pattern.
The board card in the center is the discard pile.

== The Hand

The hand consists of three rounds of betting, drawing, and spikes.
Then there's a final fourth betting round.

=== Betting Phase

Betting is modeled after the ante/bring-in system in stud poker. 
It is fixed-limit betting with a max of one bet plus three raises.
The first two betting rounds are small bet and last two are big bet size.

The first betting round has a mandatory bring-in bet from the player with the highest absolute value face-up card.
If there's a tie, positive number pays bring-in and after that whichever one is left of the dealer.

=== Draw Phase

Starting to the left of the dealer, each player can choose one of three actions:

[discrete]
==== Buy board card

The player can pay the main pot ante for a card from the board.
The player can indicate this non-verbally by placing payment on the desired board card.

The payment goes to the sabacc pot.
They can choose to take the card only or swap with a card from their hand.
The acquired board card will become a face-up card.
A player cannot swap their last pocket card for a board card.
A player cannot have more than five cards in their hand.

If the player keeps the board card without swapping, the dealer replaces the missing board card with one from the top of the discard pile.
If the discard pile is empty after replacing, the dealer places a card in the discard pile from the stub. 

[discrete]
==== Draw from the Stub

Draw for free from the stub.
The player can indicate this non-verbally by double-tapping the table.

The drawn card can be added to either the face-up or the face-down cards in the hand. 
The player also has the option of discarding any card, including the drawn card.
The discarded card is laid face-up on the discard pile.

In the rare case that the stub is exhausted, players can only take from the board, but without being required to pay to the sabacc pot.

[discrete]
==== Stay

Don't do anything.
Wave your hand over your face-up cards if you want to pass on taking a card.

=== Spike Phase

The dealer rolls the dice.

If they roll doubles (except spikes), all players turn in their pocket cards to the dealer.
The dealer may keep track what number of pocket cards each player had with tokens.
The dealer shuffles the discarded pocket cards and the stub together.
Each player is dealt the same number of cards they turned in.

If double spikes are rolled, both face-up and face-down cards are shuffled with the stub.
Players are dealt three cards face-down and one face-up like an initial deal.

<<<

== The Showdown

Last aggressor shows their hand first.
Best hand takes the main pot.
Winner takes the sabacc pot if it's Banthas Wild or better.

.Hand Rankings
[cols="^1,^2,^4,^2,>1"]
|===
| Rank | Name | Description | Example | Odds Against

| 1
| Dreadnoughts
| 4-of-a-kind 10s and Sylops
| +10 +10 0 -10 -10
| 360,500

| 2
| Rhylet Neat
| Same integer 3-of-a-kind and same integer pair
| +4 +4 +4 -6 -6
| 360,500

| 3
| Krayt Dragon
| Same integer 3-of-a-kind and Sylops
| 0 +3 +3 +3 -9
| 179,750

| 4
| Idiots Full
| Both Sylops and same integer pair
| 0 0 +3 +3 -6
| 71,900

| 5
| Echelon
| Uneven 4-of-a-kind and balancer card
| +1 +1 +1 -1 -2 
| 71,900

| 6
| Fleet
| 4-of-a-kind (except 10s) and Sylops
| +7 +7 0 -7 -7 
| 39,944

| 7
| Tusken File
| same integer 3-of-a-kind and 1 opposite card
| +3 +3 +3 -9 
| 30,990

| 8
| Rhylet Stirred
| Mixed integer 3-of-a-kind and pair
| +2 +2 -2 -1 -1
| 23,966

| 9
| Uttini!
| 0 +1 +2 +3 -6 or inverse
| 0 -1 -2 -3 +6
| 19,971

| 10
| Gee Whizz!
| +1 +2 +3 +4 -10 or inverse
| -1 -2 -3 -4 +10
| 13,314

| 11 
| Dewbacks 
| same integer 3-of-a-kind 5-card hand
| +3 +3 +3 -7 -2 
| 13,314

| 12
| Squadron
| 4-of-a-kind
| -2 -2 +2 +2 
| 6,197

| 13
| The Idiots
| Both Sylops cards, with pair or 3 rainbow cards. Pair beats rainbow
| 0 0 -3 +3 +
0 0 -1 -2 +3
| 2,970

| 14
| Idiot's Array
| 4-straight and Sylops
| 0 +4 -5 -6 +7
| 2,852

| 15
| Banthas Wild
| Mixed integer 3-of-a-kind
| +3 +3 -3 -2 -1
| 665

| 16
| Straight Khyron
| 4-straight
| +2 -3 -4 +5
| 491

| 17
| Yee-Haa
| Two-pair and Sylops
| 0 -2 +2 -3 +3 
| 221

| 18
| Rule of Two
| Two-pair
| -7 +7 -9 +9
| 76

| 19
| Sabacc
| Sum equals zero. Pair beats other tiebreakers
| +1 +4 -3 -2
|

| 20 
| Nuhlrek
| Sum does not equal zero. Closest to zero wins
| +2 +3 -4 -8
|

|===

.Tiebreakers
. Most cards
. Highest absolute value
. Highest absolute value card
. Highest positive value card

If none of these work, do a single blind draw from the deck.
Recalculate the sums to determine winner.

<<<

[appendix]
== Common Betting Structures for Cash Games

|===
| Main Pot Ante | Sabacc Pot Ante | Bring-in | Small Bet | Big Bet | Max Buy-in

| 3¢
| 2¢
| 10¢
| 25¢
| 50¢
| $20

| 5¢
| 5¢
| 20¢
| 50¢
| $1
| $40

|===

// https://www.pokerlistings.com/poker-rules-7-card-stud
