= Sabacc House Rules

== The Deal

Players place antes to the main pot and the sabacc pot.
Dealer shuffles the deck gives three down cards and one up card to each player.
The dealer lays seven cards face-up on the board in a "flower" pattern.
The board card in the center is the discard pile.

== The Hand

The hand consists of three rounds of betting, drawing, and spikes.
Then there's a final fourth betting round.

=== Betting Phase

Blinds are similar to Texas hold'em except that the small blinds pays to the Sabacc pot while the big blind pays to the main pot.

Sabacc is by default no-limit. Refer to Tournament Director's Association rules for the nuances of betting.

=== Draw Phase

Starting to the left of the dealer, each player can choose one of three actions:

[discrete]
==== Buy board card

The player can pay a small amount for a card from the board.
The blinds schedule will dictate the exact cost.

The payment goes to the sabacc pot.
They can choose to take the card only or swap with a card from their hand.
The acquired board card will become a face-up card.
A player cannot swap their last pocket card for a board card.
A player cannot have more than five cards in their hand.

If the player keeps the board card without swapping, the dealer replaces the missing board card with one from the top of the discard pile.
If the discard pile is empty after replacing, the dealer places a card in the discard pile from the stub. 

To signal buying a board card, place payment on the desired card on the board.
In the case that the player wishes to swap with the board, they need to throw the discarded card next to the board before payment.

[discrete]
==== Draw from the Stub

Draw for free from the stub.

The player can indicate that they wish to draw by double-tapping the table.
The dealer will lay a card from the stub face-down in front of the player.

The player will peak at the card and can take one of the following actions:

* Take the drawn card and add to face-down cards
* Discard a card from the hand FIRST, then take the drawn card
* Push back the drawn card to discard it. The card is mucked by the dealer

In the rare case that the stub is exhausted, players can only take from the board, but without being required to pay to the sabacc pot.

[discrete]
==== Stay

Don't do anything.
Wave your hand over your face-up cards if you want to pass on taking a card.

=== Spike Phase

Starting to the left of the button, players will be given an opportunity to turn any face-down cards into face-up cards to protect them from the spike dice.
The player must always have at least one face-down card.

The button will then roll the dice.

If they roll doubles (except spikes), all players turn in their pocket cards to the dealer.
The dealer may keep track what number of pocket cards each player had with tokens.
The dealer shuffles the discarded pocket cards and the stub together.
Each player is dealt the same number of cards they turned in.

If double spikes are rolled, the face-down cards are mixed the same as with normal doubles.
In addtion, each player needs to pick a face-up card.
The face-up cards are shuffled and dealt, one to each player.

<<<

== The Showdown

Last aggressor shows their hand first.
Best hand takes the main pot.
Winner takes the sabacc pot if it's Banthas Wild or better.

.Hand Rankings
[cols="^1,^2,^4,^2,>1"]
|===
| Rank | Name | Description | Example | Odds Against

| 1
| Dreadnoughts
| 4-of-a-kind 10s and Sylops
| +10 +10 0 -10 -10
| 360,500

| 2
| Rhylet Neat
| Same integer 3-of-a-kind and same integer pair
| +4 +4 +4 -6 -6
| 360,500

| 3
| Krayt Dragon
| Same integer 3-of-a-kind and Sylops
| 0 +3 +3 +3 -9
| 179,750

| 4
| Idiots Full
| Both Sylops and same integer pair
| 0 0 +3 +3 -6
| 71,900

| 5
| Echelon
| Uneven 4-of-a-kind and balancer card
| +1 +1 +1 -1 -2 
| 71,900

| 6
| Fleet
| 4-of-a-kind (except 10s) and Sylops
| +7 +7 0 -7 -7 
| 39,944

| 7
| Tusken File
| same integer 3-of-a-kind and 1 opposite card
| +3 +3 +3 -9 
| 30,990

| 8
| Rhylet Stirred
| Mixed integer 3-of-a-kind and pair
| +2 +2 -2 -1 -1
| 23,966

| 9
| Uttini!
| 0 +1 +2 +3 -6 or inverse
| 0 -1 -2 -3 +6
| 19,971

| 10
| Gee Whizz!
| +1 +2 +3 +4 -10 or inverse
| -1 -2 -3 -4 +10
| 13,314

| 11 
| Dewbacks 
| same integer 3-of-a-kind 5-card hand
| +3 +3 +3 -7 -2 
| 13,314

| 12
| Squadron
| 4-of-a-kind
| -2 -2 +2 +2 
| 6,197

| 13
| The Idiots
| Both Sylops cards
| 0 0 -3 +3 +
0 0 -1 -2 +3
| 2,970

| 14
| Idiot's Array
| 4-straight and Sylops
| 0 +4 -5 -6 +7
| 2,852

| 15
| Banthas Wild
| Mixed integer 3-of-a-kind
| +3 +3 -3 -2 -1
| 665

| 16
| Straight Khyron
| 4-straight
| +2 -3 -4 +5
| 491

| 17
| Yee-Haa
| Two-pair and Sylops
| 0 -2 +2 -3 +3 
| 221

| 18
| Rule of Two
| Two-pair
| -7 +7 -9 +9
| 76

| 19
| Sabacc
| Sum equals zero. Pair > Sylops.
| +1 +4 -3 -2
|

| 20 
| Nuhlrek
| Sum does not equal zero. Closest to zero wins
| +2 +3 -4 -8
|

|===

.Tiebreakers
. Most cards
. Highest absolute value
. Highest absolute value card
. Highest positive value card

If none of these work, do a single blind draw from the deck.
Recalculate the sums to determine winner.

<<<

[appendix]
== Example Blinds Schedule

|===
| Level | Sabacc Blind (Small) | Main Blind (Big) | Board Card Price | Time

| 1
| $50
| $100
| $25
| +0:00

| 2
| $100
| $200
| $50
| +0:20

| 3
| $200
| $400
| $75
| +0:40

| 4
| $400
| $800
| $150
| +1:00

| 5
| $800
| $1600
| $300
| +1:20

| 6
| $1500
| $3000
| $500
| +1:40

| 7
| $3000
| $6000
| $1000
| +2:00

|===

// https://www.pokerlistings.com/poker-rules-7-card-stud
